version: '3.9'

services:
  app:
    image: express-docker
    restart: always
    # ports:
    #   - "3000-3010:3000"
    # environment:
    #   - NODE_ENV=production
  
  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    ports:
      - "80:3000"
